matrix:
  include:
  - language: java
    jdk: openjdk8
    cache:
      directories:
      - "$HOME/.m2/repository"
  - language: python
    if: branch = master
    python: 3.7.1
    cache:
      directories:
      - "$HOME/.cache"
      - "$HOME/virtualenv"
    script:
      - "./deploy-docs.sh"
