matrix:
  include:
    - language: java
      jdk: openjdk8
      cache:
        directories:
          - "$HOME/.m2/repository"
    - language: python
      python: "3.7.1"
      cache:
        directories:
          - "$HOME/.cache"
          - "$HOME/virtualenv"
      script:
        - pip3 install mkdocs
        - pip3 install pygments
        - pip3 install pymdown-extensions
        - pip3 install pyyaml
        - pip3 install mkdocs-markdownextradata-plugin
        - git clone https://github.com/Dans-labs/mkdocs-dans
        - pushd mkdocs-dans; python3 build.py pack; popd
        - mkdocs build
        - ./deploy-docs.sh
      env:
        global:
          secure: "ZzBogTXUBX6Fm8g6qnmm6AGEpSipBaZ7UcGf/3wIESkDQW70DE9KR6gL7cZSii9Ajk9ug1FjBGquk47LgJ7vGcmKDh8Eb2T3zo0zCmdeEZWIhtu/q1w+ZMbjorEb60IXpCh/dAjXeSLeKcXRmE6+1VZg6u+HYzLkvITelg1penr4PleJbhmhIE6KoVgeRZDMSMFUjHKWxQvzgkmZhYjyxLoaErjLgHONNX2f0K7iJ5uZVDpoWScBBh3arMNzU6niryq5HaURWKOPkZ9UPLRBYbJG5EbWijwnFipyfhW6PBPSfLR1JTOcUQWCPGB+BOU2dV9/Nr1ModFP/BC1YbBjxzDFf06G/2jkzM3h6zYoOMMJXqNAmdrvelYsd7QwVoYQCXvVBf0Tb2IhJ5k9wnp+CFmtLYyrk6KPxBtDCrYi9FBGHUwqJA20x85QeO44jsvFFswbNnCIYf+rYTGDBu6R3zHjU4qvhUa239TwLxNT8pyb3J2A9mZeLCpvFFVPGuNvcNF7fwdyAPwQ+iQszmy839ZRQuCwLjdL/1XnHzjWPv1MuphzAbdvJMUsW8CN+5/YvtkAHzyy6RFMgFN0pOQpDXOkDYu2oxKd3p5+RWJ9xuStV5rwAqLGIsnMqKcRtV5ChdZvKxR9d5HjATGcmgtjbgJqef9aUVuSqR7e1RCqgUk="
